/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  fragment MerchantClientTransactionSessionBaseFragment on MerchantClientTransactionSession {\n    id\n    action\n    status\n    providerCode\n    providerStatus\n    providerError\n    providerLastSyncedAt\n    providerLastVerifiedAt\n\n    token\n    tokenExpiresAt\n\n    payload\n\n    amount\n    currency\n\n    merchantInternalCustomerCode\n    merchantInternalTransactionCode\n\n    startedAt\n    completedAt\n    canceledAt\n\n    storePaymentMethod\n\n    transactionProviderId\n    paymentMethodId\n    paymentPlanId\n\n    createdAt\n    updatedAt\n\n    deviceId\n    deviceIp\n    deviceBrowser\n    deviceOS\n    deviceName\n    deviceType\n\n    billingFirstName\n    billingLastName\n    billingEmail\n    billingPhone\n    billingAddressLine1\n    billingAddressLine2\n    billingAddressCity\n    billingAddressState\n    billingAddressCountry\n    billingAddressPostalCode\n\n    shippingFirstName\n    shippingLastName\n    shippingEmail\n    shippingPhone\n    shippingAddressLine1\n    shippingAddressLine2\n    shippingAddressCity\n    shippingAddressState\n    shippingAddressCountry\n    shippingAddressPostalCode\n\n    userFirstName\n    userLastName\n    userEmail\n    userPhone\n    userBirthDate\n    userLocale\n    userLegalIdentifier\n    userLegalIdentifierType\n    userAddressLine1\n    userAddressLine2\n    userAddressCity\n    userAddressState\n    userAddressCountry\n    userAddressPostalCode\n  }\n": typeof types.MerchantClientTransactionSessionBaseFragmentFragmentDoc,
    "\n  fragment MerchantTransactionProviderFragment on MerchantTransactionProvider {\n    id\n    provider\n    providerCode\n    status\n    applicationId\n    merchantId\n    createdAt\n    updatedAt\n  }\n": typeof types.MerchantTransactionProviderFragmentFragmentDoc,
    "\n  fragment MerchantClientTransactionSessionFragment on MerchantClientTransactionSession {\n    ...MerchantClientTransactionSessionBaseFragment\n\n    transactionProvider {\n      ...MerchantTransactionProviderFragment\n    }\n  }\n": typeof types.MerchantClientTransactionSessionFragmentFragmentDoc,
    "\n  query ClientPublicTransactionSessionBaseConfig(\n    $merchantPublicId: String!\n    $transactionSessionId: String\n    $transactionProvider: TRANSACTION_PROVIDER\n  ) {\n    clientPublicTransactionSessionBaseConfig(\n      merchantPublicId: $merchantPublicId\n      transactionSessionId: $transactionSessionId\n      transactionProvider: $transactionProvider\n    ) {\n      provider\n      data {\n        ... on MerchantClientTransactionSessionNuveiBaseConfig {\n          provider\n          merchantId\n          merchantSiteId\n          env\n        }\n        ... on MerchantClientTransactionSessionGenericBaseConfig {\n          provider\n          publicKey\n        }\n      }\n    }\n  }\n": typeof types.ClientPublicTransactionSessionBaseConfigDocument,
    "\n  query ClientPublicTransactionSession(\n    $merchantPublicId: String!\n    $transactionSessionId: String!\n  ) {\n    clientPublicTransactionSession(\n      merchantPublicId: $merchantPublicId\n      transactionSessionId: $transactionSessionId\n    ) {\n      provider\n      baseConfig {\n        ... on MerchantClientTransactionSessionNuveiBaseConfig {\n          provider\n          merchantId\n          merchantSiteId\n          env\n        }\n        ... on MerchantClientTransactionSessionGenericBaseConfig {\n          provider\n          publicKey\n        }\n      }\n      \n      transactionSession {\n        ...MerchantClientTransactionSessionFragment\n      }\n    }\n  }\n": typeof types.ClientPublicTransactionSessionDocument,
};
const documents: Documents = {
    "\n  fragment MerchantClientTransactionSessionBaseFragment on MerchantClientTransactionSession {\n    id\n    action\n    status\n    providerCode\n    providerStatus\n    providerError\n    providerLastSyncedAt\n    providerLastVerifiedAt\n\n    token\n    tokenExpiresAt\n\n    payload\n\n    amount\n    currency\n\n    merchantInternalCustomerCode\n    merchantInternalTransactionCode\n\n    startedAt\n    completedAt\n    canceledAt\n\n    storePaymentMethod\n\n    transactionProviderId\n    paymentMethodId\n    paymentPlanId\n\n    createdAt\n    updatedAt\n\n    deviceId\n    deviceIp\n    deviceBrowser\n    deviceOS\n    deviceName\n    deviceType\n\n    billingFirstName\n    billingLastName\n    billingEmail\n    billingPhone\n    billingAddressLine1\n    billingAddressLine2\n    billingAddressCity\n    billingAddressState\n    billingAddressCountry\n    billingAddressPostalCode\n\n    shippingFirstName\n    shippingLastName\n    shippingEmail\n    shippingPhone\n    shippingAddressLine1\n    shippingAddressLine2\n    shippingAddressCity\n    shippingAddressState\n    shippingAddressCountry\n    shippingAddressPostalCode\n\n    userFirstName\n    userLastName\n    userEmail\n    userPhone\n    userBirthDate\n    userLocale\n    userLegalIdentifier\n    userLegalIdentifierType\n    userAddressLine1\n    userAddressLine2\n    userAddressCity\n    userAddressState\n    userAddressCountry\n    userAddressPostalCode\n  }\n": types.MerchantClientTransactionSessionBaseFragmentFragmentDoc,
    "\n  fragment MerchantTransactionProviderFragment on MerchantTransactionProvider {\n    id\n    provider\n    providerCode\n    status\n    applicationId\n    merchantId\n    createdAt\n    updatedAt\n  }\n": types.MerchantTransactionProviderFragmentFragmentDoc,
    "\n  fragment MerchantClientTransactionSessionFragment on MerchantClientTransactionSession {\n    ...MerchantClientTransactionSessionBaseFragment\n\n    transactionProvider {\n      ...MerchantTransactionProviderFragment\n    }\n  }\n": types.MerchantClientTransactionSessionFragmentFragmentDoc,
    "\n  query ClientPublicTransactionSessionBaseConfig(\n    $merchantPublicId: String!\n    $transactionSessionId: String\n    $transactionProvider: TRANSACTION_PROVIDER\n  ) {\n    clientPublicTransactionSessionBaseConfig(\n      merchantPublicId: $merchantPublicId\n      transactionSessionId: $transactionSessionId\n      transactionProvider: $transactionProvider\n    ) {\n      provider\n      data {\n        ... on MerchantClientTransactionSessionNuveiBaseConfig {\n          provider\n          merchantId\n          merchantSiteId\n          env\n        }\n        ... on MerchantClientTransactionSessionGenericBaseConfig {\n          provider\n          publicKey\n        }\n      }\n    }\n  }\n": types.ClientPublicTransactionSessionBaseConfigDocument,
    "\n  query ClientPublicTransactionSession(\n    $merchantPublicId: String!\n    $transactionSessionId: String!\n  ) {\n    clientPublicTransactionSession(\n      merchantPublicId: $merchantPublicId\n      transactionSessionId: $transactionSessionId\n    ) {\n      provider\n      baseConfig {\n        ... on MerchantClientTransactionSessionNuveiBaseConfig {\n          provider\n          merchantId\n          merchantSiteId\n          env\n        }\n        ... on MerchantClientTransactionSessionGenericBaseConfig {\n          provider\n          publicKey\n        }\n      }\n      \n      transactionSession {\n        ...MerchantClientTransactionSessionFragment\n      }\n    }\n  }\n": types.ClientPublicTransactionSessionDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment MerchantClientTransactionSessionBaseFragment on MerchantClientTransactionSession {\n    id\n    action\n    status\n    providerCode\n    providerStatus\n    providerError\n    providerLastSyncedAt\n    providerLastVerifiedAt\n\n    token\n    tokenExpiresAt\n\n    payload\n\n    amount\n    currency\n\n    merchantInternalCustomerCode\n    merchantInternalTransactionCode\n\n    startedAt\n    completedAt\n    canceledAt\n\n    storePaymentMethod\n\n    transactionProviderId\n    paymentMethodId\n    paymentPlanId\n\n    createdAt\n    updatedAt\n\n    deviceId\n    deviceIp\n    deviceBrowser\n    deviceOS\n    deviceName\n    deviceType\n\n    billingFirstName\n    billingLastName\n    billingEmail\n    billingPhone\n    billingAddressLine1\n    billingAddressLine2\n    billingAddressCity\n    billingAddressState\n    billingAddressCountry\n    billingAddressPostalCode\n\n    shippingFirstName\n    shippingLastName\n    shippingEmail\n    shippingPhone\n    shippingAddressLine1\n    shippingAddressLine2\n    shippingAddressCity\n    shippingAddressState\n    shippingAddressCountry\n    shippingAddressPostalCode\n\n    userFirstName\n    userLastName\n    userEmail\n    userPhone\n    userBirthDate\n    userLocale\n    userLegalIdentifier\n    userLegalIdentifierType\n    userAddressLine1\n    userAddressLine2\n    userAddressCity\n    userAddressState\n    userAddressCountry\n    userAddressPostalCode\n  }\n"): (typeof documents)["\n  fragment MerchantClientTransactionSessionBaseFragment on MerchantClientTransactionSession {\n    id\n    action\n    status\n    providerCode\n    providerStatus\n    providerError\n    providerLastSyncedAt\n    providerLastVerifiedAt\n\n    token\n    tokenExpiresAt\n\n    payload\n\n    amount\n    currency\n\n    merchantInternalCustomerCode\n    merchantInternalTransactionCode\n\n    startedAt\n    completedAt\n    canceledAt\n\n    storePaymentMethod\n\n    transactionProviderId\n    paymentMethodId\n    paymentPlanId\n\n    createdAt\n    updatedAt\n\n    deviceId\n    deviceIp\n    deviceBrowser\n    deviceOS\n    deviceName\n    deviceType\n\n    billingFirstName\n    billingLastName\n    billingEmail\n    billingPhone\n    billingAddressLine1\n    billingAddressLine2\n    billingAddressCity\n    billingAddressState\n    billingAddressCountry\n    billingAddressPostalCode\n\n    shippingFirstName\n    shippingLastName\n    shippingEmail\n    shippingPhone\n    shippingAddressLine1\n    shippingAddressLine2\n    shippingAddressCity\n    shippingAddressState\n    shippingAddressCountry\n    shippingAddressPostalCode\n\n    userFirstName\n    userLastName\n    userEmail\n    userPhone\n    userBirthDate\n    userLocale\n    userLegalIdentifier\n    userLegalIdentifierType\n    userAddressLine1\n    userAddressLine2\n    userAddressCity\n    userAddressState\n    userAddressCountry\n    userAddressPostalCode\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment MerchantTransactionProviderFragment on MerchantTransactionProvider {\n    id\n    provider\n    providerCode\n    status\n    applicationId\n    merchantId\n    createdAt\n    updatedAt\n  }\n"): (typeof documents)["\n  fragment MerchantTransactionProviderFragment on MerchantTransactionProvider {\n    id\n    provider\n    providerCode\n    status\n    applicationId\n    merchantId\n    createdAt\n    updatedAt\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment MerchantClientTransactionSessionFragment on MerchantClientTransactionSession {\n    ...MerchantClientTransactionSessionBaseFragment\n\n    transactionProvider {\n      ...MerchantTransactionProviderFragment\n    }\n  }\n"): (typeof documents)["\n  fragment MerchantClientTransactionSessionFragment on MerchantClientTransactionSession {\n    ...MerchantClientTransactionSessionBaseFragment\n\n    transactionProvider {\n      ...MerchantTransactionProviderFragment\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query ClientPublicTransactionSessionBaseConfig(\n    $merchantPublicId: String!\n    $transactionSessionId: String\n    $transactionProvider: TRANSACTION_PROVIDER\n  ) {\n    clientPublicTransactionSessionBaseConfig(\n      merchantPublicId: $merchantPublicId\n      transactionSessionId: $transactionSessionId\n      transactionProvider: $transactionProvider\n    ) {\n      provider\n      data {\n        ... on MerchantClientTransactionSessionNuveiBaseConfig {\n          provider\n          merchantId\n          merchantSiteId\n          env\n        }\n        ... on MerchantClientTransactionSessionGenericBaseConfig {\n          provider\n          publicKey\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query ClientPublicTransactionSessionBaseConfig(\n    $merchantPublicId: String!\n    $transactionSessionId: String\n    $transactionProvider: TRANSACTION_PROVIDER\n  ) {\n    clientPublicTransactionSessionBaseConfig(\n      merchantPublicId: $merchantPublicId\n      transactionSessionId: $transactionSessionId\n      transactionProvider: $transactionProvider\n    ) {\n      provider\n      data {\n        ... on MerchantClientTransactionSessionNuveiBaseConfig {\n          provider\n          merchantId\n          merchantSiteId\n          env\n        }\n        ... on MerchantClientTransactionSessionGenericBaseConfig {\n          provider\n          publicKey\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query ClientPublicTransactionSession(\n    $merchantPublicId: String!\n    $transactionSessionId: String!\n  ) {\n    clientPublicTransactionSession(\n      merchantPublicId: $merchantPublicId\n      transactionSessionId: $transactionSessionId\n    ) {\n      provider\n      baseConfig {\n        ... on MerchantClientTransactionSessionNuveiBaseConfig {\n          provider\n          merchantId\n          merchantSiteId\n          env\n        }\n        ... on MerchantClientTransactionSessionGenericBaseConfig {\n          provider\n          publicKey\n        }\n      }\n      \n      transactionSession {\n        ...MerchantClientTransactionSessionFragment\n      }\n    }\n  }\n"): (typeof documents)["\n  query ClientPublicTransactionSession(\n    $merchantPublicId: String!\n    $transactionSessionId: String!\n  ) {\n    clientPublicTransactionSession(\n      merchantPublicId: $merchantPublicId\n      transactionSessionId: $transactionSessionId\n    ) {\n      provider\n      baseConfig {\n        ... on MerchantClientTransactionSessionNuveiBaseConfig {\n          provider\n          merchantId\n          merchantSiteId\n          env\n        }\n        ... on MerchantClientTransactionSessionGenericBaseConfig {\n          provider\n          publicKey\n        }\n      }\n      \n      transactionSession {\n        ...MerchantClientTransactionSessionFragment\n      }\n    }\n  }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;